name: Client Tester

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: Install
        run: npm ci --prefix client/
      - name: Test
        run: npm test a --prefix client/ -- --coverage
      - name: Build
        run: CI= npm run build --prefix client/