name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: t1.adrianobp.dev
          username: adriano
          password: ${{ secrets.ssh_password }}
          port: 22
          script: |
            cd /home/adriano/projects/node-react-project-template
            systemctl stop node-react-project-template
            git checkout master
            git pull
            npm run build --prefix client/
            systemctl start node-react-project-template
