name: Linter

on:
  push:
    branches: [main]
    paths:
    - 'client/src/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: Build
      - run: npm ci
      - run: npm run build
      - name: Linter
        run: npx eslint "client/src/**"